[project]
name = "mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-groq>=0.3.7",
    "langchain-openai>=0.3.32",
    "mcp-use>=1.3.10",
    "python-dotenv>=1.1.1",
]
